name: Build & Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-16.04
    name: Run Tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --no-audit
      - run: npm test
      - run: npm run test:e2e
  build:
    runs-on: ubuntu-16.04
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --no-audit
      - run: npm run build
